name: Build and deploy ASP.Net Core app to Azure Web App - GameBoardTracker

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore Backend/P2.API/P2.API.csproj

      - name: Build with dotnet
        run: dotnet build Backend/P2.API/P2.API.csproj --configuration Release

      - name: Publish with dotnet
        run: dotnet publish Backend/P2.API/P2.API.csproj -c Release -o "${{ github.workspace }}/myapp"

      # Check if published files exist
      - name: Check published files
        run: ls -R "${{ github.workspace }}/myapp"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{ github.workspace }}/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write 
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Check downloaded files
        run: ls -R "./myapp"  # Confirm downloaded artifact location

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'GameBoardTracker'  # Your Azure App Service name
          slot-name: 'Production'
          package: './myapp'  # This should point to the published output directory
