# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# yml file
name: Build and deploy ASP.Net Core app to Azure Web App - gameBoardTracker

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build with dotnet
        run: dotnet build Backend/P2.API/P2.API.csproj --configuration Release

      - name: Publish with dotnet
        run: dotnet publish Backend/P2.API/P2.API.csproj -c Release -o "${{ env.DOTNET_ROOT }}\myapp"

      - name: Zip published output (if needed)
        run: |
          $source = "${{ env.DOTNET_ROOT }}\myapp"
          $zipFile = "${{ env.DOTNET_ROOT }}\myapp.zip"
          if (Test-Path $source) {
            Compress-Archive -Path "$source\*" -DestinationPath $zipFile
          } else {
            Write-Host "Directory does not exist."
          }

      - name: Upload zipped artifact for deployment job (if zipped)
        uses: actions/upload-artifact@v4
        with:
          name: myapp-zip
          path: "${{ env.DOTNET_ROOT }}/myapp.zip"

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
    permissions:
      id-token: write # This is required for requesting the JWT

    steps:
      - name: Download artifact from build job (adjusted)
        uses: actions/download-artifact@v4
        with:
          name: myapp-zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID }} # Ensure this secret is set
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID }} # Ensure this secret is set
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID }} # Ensure this secret is set
          # client-secret: ${{ secrets.AZURE_CLIENT_SECRET }} # If using a secret

      - name: Deploy to Azure Web App (ensure correct package path)
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'gameBoardTracker'
          slot-name: 'Production' # Change if you're not using slots.
          package: '${{ github.workspace }}\myapp.zip' # Adjust based on whether you zipped it.
